### ISSUE TITLE
Why MainDeployerMBean and SubDeployer support was discontinued in wildfly which was present in jboss 5.1 AS

### ISSUE THREAD

**Issue by sashivit** [wildfly/wildfly#10668]

**Comment by jaikiran** [comment]
Starting JBoss AS7 the underlying server architecture was completely rewritten. The classes you mention are no longer relevant in these newer versions of the server.

P.S: Questions like these are answered in the WildFly forum (JBoss AS is now called WildFly) at https://developer.jboss.org/en/wildfly instead of here.

**Comment by sashivit** [comment]
I had asked there but till now no response. Atleast, can you point to documentation for custom deployers in wildfly (For our own package files)?

**Comment by jaikiran** [comment]
>> Atleast, can you point to documentation for custom deployers in wildfly (For our own package files)?

This might help https://docs.jboss.org/author/display/WFLY10/Extending+WildFly
